stages:
    - preparation
    - testing

.parallel-hidden-job:
    parallel:
        matrix:
            -   TYPO3: [ '^12.0' ]
                PHP: [ '8.1', '8.2', '8.3' ]

default:
    before_script:
        # Update image
        - apt-get update -yqq
        - apt-get install -yqq git libxml2-dev libzip-dev zip unzip gnupg2

        # Install PHP extensions
        - docker-php-ext-install intl xml zip
        - php --version

        # Install composer
        - curl -sS https://getcomposer.org/installer | php

.php:
    extends: .parallel-hidden-job
    image: php:$PHP
    before_script:
        - !reference [ default, before_script ]

composer:
    stage: preparation
    extends:
        - .php
    variables:
        COMPOSER_AUTH: |
    script:
        # Install all project dependencies
        - echo "Install dependencies with typo3/cms-core:$TYPO3"
        - php composer.phar config -g gitlab-oauth.git.netresearch.de $GITLAB_ACCESS_TOKEN
        - php composer.phar require typo3/cms-core:$TYPO3 --no-progress --no-update
        - php composer.phar require typo3/cms-scheduler:$TYPO3 --no-progress --no-update
        - php composer.phar require typo3/cms-fluid:$TYPO3 --no-progress --no-update
        - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
        - git checkout composer.json
    artifacts:
        paths:
            - .build/
        expire_in: 1 days
        when: always
    cache:
        paths:
            - .build/

phplint:
    stage: testing
    extends:
        - .php
    needs:
        - composer
    script:
        - php composer.phar ci:test:php:lint

phpstan:
    stage: testing
    extends:
        - .php
    needs:
        - composer
    script:
        - php composer.phar ci:test:php:phpstan -- --memory-limit=-1 --error-format=gitlab > phpstan-report.json
    artifacts:
        paths:
            - "phpstan-report.json"
        expire_in: 1 days
        when: always
        reports:
            codequality: "./phpstan-report.json"

rector:
    stage: testing
    extends:
        - .php
    needs:
        - composer
    script:
        - php composer.phar ci:test:php:rector

coding-style:
    stage: testing
    extends:
        - .php
    needs:
        - composer
    script:
        - php composer.phar ci:cgl -- --dry-run
